[server]
host = 0.0.0.0
port = 8000

[general]
m3u_host = http://127.0.0.1:8000
refresh_interval = 1440
track_metrics = false
use_ffmpeg = true
ffmpeg_path = /usr/bin/ffmpeg
use_streamlink = false
streamlink_path = /usr/bin/streamlink
allow_external_app = false
enable_plex_support = false
enable_ssdp = false

[provider:list1]
file =
max_streams = 1
priority = 1

[provider:list2]
file =
max_streams = 1
priority = 2

[mapping]
# grep -oP '[0-9a-f]{32}' config.ini | sort | uniq -c | sort -n | tail -n 20
# Format: original-tvg-id = index|new-tvg-id|name
