[server]
host = 0.0.0.0
port = 8000

[general]
m3u_host = http://127.0.0.1:8000
refresh_interval = 1440
track_metrics = false
use_ffmpeg = true
ffmpeg_path = /usr/bin/ffmpeg
use_streamlink = false
streamlink_quality = 720p,480p,best
allow_external_app = false
enable_plex_support = false
enable_ssdp = false
stream_chunk_size = 9400
stream_read_poll_interval = 1.0
stream_cleanup_timeout = 5.0

[provider:list1]
file =
max_streams = 1
priority = 1

[provider:list2]
file =
max_streams = 1
priority = 2

[mapping]
# Channels are matched by normalizing the name (lowercase, no spaces, "HD" removed)
# Format: normalized-name = index|new-tvg-id|name
